# Generated by Django 3.0.5 on 2020-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blob_data', models.TextField(blank=True, null=True)),
                ('ground_truth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('favorite_movie', models.CharField(max_length=30)),
                ('challenge_question', models.CharField(max_length=100)),
                ('world_question', models.CharField(max_length=100)),
            ],
        ),
    ]
