# Generated by Django 3.0.5 on 2020-06-15 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blob_data_raw', models.BinaryField(blank=True, null=True)),
                ('blob_data_float', models.BinaryField(blank=True, null=True)),
                ('blob_data_mfcc', models.BinaryField(blank=True, null=True)),
                ('ground_truth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('favorite_movie', models.CharField(blank=True, max_length=30, null=True)),
                ('challenge_question', models.CharField(blank=True, max_length=100, null=True)),
                ('world_question', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=60, null=True)),
                ('person_statement', models.CharField(blank=True, max_length=100, null=True)),
                ('chatbot_response', models.CharField(blank=True, max_length=100, null=True)),
                ('person_statement_date', models.DateTimeField(default=datetime.datetime(2020, 6, 15, 13, 23, 48, 47614, tzinfo=utc))),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
