# Generated by Django 3.0.5 on 2020-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='blob_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
