# Generated by Django 3.0.5 on 2020-06-16 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('search_text', models.CharField(max_length=255)),
                ('conversation', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('in_response_to', models.CharField(blank=True, max_length=255, null=True)),
                ('search_in_response_to', models.CharField(max_length=255)),
                ('persona', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tag_association',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='raw_conversation',
            name='person_statement_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 24, 19, 812765, tzinfo=utc)),
        ),
    ]
