# Generated by Django 3.0.5 on 2020-06-16 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200616_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_conversation',
            name='person_statement_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 37, 41, 183543, tzinfo=utc)),
        ),
    ]
