# Generated by Django 3.0.5 on 2020-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200608_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='blob_data',
            new_name='blob_data_mfcc',
        ),
        migrations.AddField(
            model_name='memory',
            name='blob_data_raw',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
