# Generated by Django 3.0.5 on 2020-06-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200608_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='blob_data_1',
            new_name='blob_data',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='blob_data_2',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='blob_data_3',
        ),
    ]
