# Generated by Django 3.0.5 on 2020-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200609_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='blob_data_float',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
