# Generated by Django 3.0.5 on 2020-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_memory_blob_data_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='challenge_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='world_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
