# Generated by Django 3.0.5 on 2020-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200612_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(blank=True, max_length=60, null=True)),
                ('person_response', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.TimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
